# PUPNET DEPLOY: 1.10.0
# Use: 'pupnet --help conf' for information.

# APP PREAMBLE
AppBaseName = AuroraAssetEditorLinux
AppFriendlyName = Aurora Asset Editor Linux
AppId = com.ngf.auroraasseteditorlinux
AppVersionRelease = 1.0.0[1]
AppShortSummary = A tool for editing Aurora assets.
AppDescription = """
A tool for modifying Aurora game assets on Linux.
It supports file extraction and modification, featuring a graphical interface built with Avalonia.
"""

AppLicenseId = LicenseRef-Proprietary
AppLicenseFile = 
AppChangeFile = 

# PUBLISHER
PublisherName = NGF
PublisherId = com.ngf
PublisherCopyright = Copyright (C) NGF 2026
PublisherLinkName = Home Page
PublisherLinkUrl = 
PublisherEmail = 
PublisherGpgKeyId = 

# DESKTOP INTEGRATION
DesktopNoDisplay = false
DesktopTerminal = false
DesktopFile = 
StartCommand = 
PrimeCategory = 
MetaFile = 
IconFiles = """
Icons/Aurour.64x64.png
Icons/Aurour.128x128.png
Icons/Aurour.256x256.png
Icons/Aurour.512x512.png
"""

# DOTNET PUBLISH
DotnetProjectPath = AuroraAssetEditorLinux.csproj 
DotnetPublishArgs = -p:Version=${APP_VERSION} --self-contained true
DotnetPostPublish = 
DotnetPostPublishOnWindows = 

# PACKAGE OUTPUT
PackageName = AuroraAssetEditorLinux
OutputDirectory = Deploy/OUT

# APPIMAGE OPTIONS
AppImageArgs = 
AppImageRuntimePath =  
AppImageVersionOutput = false

# FLATPAK OPTIONS
FlatpakPlatformRuntime = org.freedesktop.Platform
FlatpakPlatformSdk = org.freedesktop.Sdk
FlatpakPlatformVersion = 25.08
FlatpakFinishArgs = """
    --socket=x11
"""
FlatpakBuilderArgs = 

# RPM OPTIONS
RpmAutoReq = false
RpmAutoProv = true
RpmRequires = """
    glibc
    libgcc
    ca-certificates
    openssl-libs
    libstdc++
    libicu
    tzdata
    krb5-libs
"""

# DEBIAN OPTIONS
DebianRecommends = """
    libc6
    libgcc-s1
    libgssapi-krb5-2
    libicu72
    libssl3
    libstdc++6
    zlib1g
"""

# WINDOWS SETUP OPTIONS
SetupGroupName = 
SetupAdminInstall = false
SetupCommandPrompt = 
SetupMinWindowsVersion = 10
SetupSignTool = 
SetupSuffixOutput = 
SetupVersionOutput = false
SetupUninstallScript = 

# ZIP OPTIONS
ZipVersionOutput = true
