<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64;win-x86</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.1.5.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <AvaloniaResource Include="Icons\Aurour.png"/> 
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) Or $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win'))">
    <None Include="AuroraAsset.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="msvcr100.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
